export const SET_CURRENCY_INFO = "SET_CURRENCY_INFO";
export const SET_LOADING = "SET_LOADING";
export const SET_CONVERTING = "SET_CONVERTING";
export const SET_CONVERTED_VALUE = "SET_CONVERTED_VALUE";
